version: '3.9'

services:
  web:
    build: .
    working_dir: /var/app
    entrypoint: /var/app/entrypoint.sh
    volumes:
      - .:/var/app
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - db
      - mailcatcher
    tty: true
    stdin_open: true
    links:
      - mailcatcher
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
