default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'db') %>

development:
  <<: *default
  database: contact_registration_development

test:
  <<: *default
  database: contact_registration_test
